### ISSUE TITLE
Request a weight file "yolov4-tiny-3l-crowdhuman-416x416"

### ISSUE THREAD

**Issue by hoangkhoiLE** [jkjung-avt/yolov4_crowdhuman#19] opened 2021-03-11 10:46 UTC
Hi @jkjung-avt , 

I would like to test the performance of the model with the weight "yolov4-tiny-3l-crowdhuman-416x416" ! Can you share me the weight file of it ? I very appreciate your work ! Thank you in advance !

Best regards

**Comment by jkjung-avt** [comment] 2021-03-11 11:54
This is a duplicate of https://github.com/jkjung-avt/yolov4_crowdhuman/issues/17#issuecomment-796643306...

@hoangkhoiLE  I have not trained a "yolov4-tiny-3l-crowdhuman-416x416" by myself.  I encourage you to do that by yourself.  With slight modifications of the code in this repo, you should be able to train such a model on Google Colab (for free!) within a few hours.

**Closed as completed** 2021-03-11 12:28 UTC

**Comment by hoangkhoiLE** [comment] 2021-03-11 12:29
Thank you I will try it !
